# CBP Form 7501 (Entry Summary) PDF → ES-003 rows for the batch audit.
#
# Real-world 7501s are machine-generated by ABI software (NetCHB, CargoWise,
# etc.), so text extraction is reliable — the fragile part is column layout,
# which varies by vendor. This parser is deliberately line/anchor based rather
# than coordinate based: the block-33 rate column ("Free", "2.5%") is the one
# token that is unmistakable on every vendor's line-item row, so entered value
# (block 32, the token before it) and duty (block 34, the token after it) are
# read relative to that anchor. Anything that cannot be read lands in
# `warnings` with page/line context — never silently dropped.

import io
import logging
import re

import pdfplumber
import PyPDF2

log = logging.getLogger("tariffcheck")


class Form7501Error(Exception):
    """Parse-level failure the endpoint maps to a 422 (code + message)."""

    def __init__(self, code, message):
        super().__init__(message)
        self.code = code
        self.message = message


class NoExtractableTextError(Form7501Error):
    """Scanned/image PDF — no text layer at all."""

    def __init__(self):
        super().__init__(
            "unreadable_file",
            "No extractable text in this PDF — it looks scanned. "
            "Upload the machine-generated 7501 from your ABI software, not a scan.",
        )


class NotA7501Error(Form7501Error):
    """Text extracted but zero HTS line items — not an entry summary."""

    def __init__(self):
        super().__init__(
            "not_a_7501",
            "No HTS line items found — this does not look like a CBP Form 7501 "
            "entry summary.",
        )


# Block 1 entry number: 3-digit filer code, 7-digit sequence, check digit.
_ENTRY_NO_RE = re.compile(r"\b(\d{3}-\d{7}-\d)\b")
# Block 12 importer number: IRS EIN based (NN-NNNNNNNXX) or SSN based.
_IMPORTER_NO_RE = re.compile(r"\b(\d{2,3}-\d{7}\s?[0-9A-Z]{0,2})\b")
_DATE_RE = re.compile(r"\b(\d{1,2})/(\d{1,2})/(\d{2,4})\b")
# HTS candidates: anything shaped like a dotted tariff number. Valid 7501
# codes must resolve to 10 digits (NNNN.NN.NNNN or USITC NNNN.NN.NN.NN);
# near-misses become warnings, never rows.
_HTS_CANDIDATE_RE = re.compile(r"\b(\d{4}\.\d{1,2}\.\d{1,4}(?:\.\d{1,2})?)\b")
# Block 33 rate column — the positional anchor for value (before) and duty (after).
_RATE_TOKEN_RE = re.compile(r"^(?:free|\d+(?:\.\d+)?%)$", re.IGNORECASE)
_MONEY_RE = re.compile(r"^\$?\d{1,3}(?:,\d{3})*(?:\.\d+)?$|^\$?\d+(?:\.\d+)?$")
_LINE_NO_RE = re.compile(r"^(\d{1,3})\b")
# Quantity units that show up next to weights/quantities on line-item rows —
# a bare two-letter uppercase token that ISN'T one of these is read as a
# line-level country of origin code.
_UNIT_TOKENS = {"KG", "NO", "LB", "PC", "PCS", "DOZ", "GR", "M2", "M3", "L", "X"}


def _extract_pages(file_bytes):
    """List of per-page line lists. pdfplumber first (better layout fidelity),
    PyPDF2 fallback. Returns [] only when neither finds any text."""
    try:
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            pages = []
            for page in pdf.pages:
                text = page.extract_text(x_tolerance=3, y_tolerance=3) or ""
                pages.append([ln.strip() for ln in text.splitlines() if ln.strip()])
            if any(pages):
                return pages
    except Exception as e:
        log.warning(f"7501 pdfplumber error: {e}")

    try:
        reader = PyPDF2.PdfReader(io.BytesIO(file_bytes))
        pages = []
        for page in reader.pages:
            text = page.extract_text() or ""
            pages.append([ln.strip() for ln in text.splitlines() if ln.strip()])
        if any(pages):
            return pages
    except Exception as e:
        log.error(f"7501 PyPDF2 error: {e}")
    return []


def _to_iso_date(mm, dd, yy):
    year = int(yy)
    if year < 100:
        year += 2000
    try:
        month, day = int(mm), int(dd)
        if not (1 <= month <= 12 and 1 <= day <= 31):
            return None
        return f"{year:04d}-{month:02d}-{day:02d}"
    except ValueError:
        return None


def _find_labeled_date(lines, label):
    """Date on the label's own line, else the first date within the next two
    lines (ABI printouts put labels on one row, values on the next)."""
    for i, line in enumerate(lines):
        if label.lower() not in line.lower():
            continue
        for candidate in lines[i:i + 3]:
            m = _DATE_RE.search(candidate)
            if m:
                return _to_iso_date(*m.groups())
    return None


def _parse_header(page1, warnings):
    header = {"entry_no": None, "entry_date": None, "importer_no": None, "origin": None}
    text = "\n".join(page1)

    m = _ENTRY_NO_RE.search(text)
    if m:
        header["entry_no"] = m.group(1)
    else:
        warnings.append("page 1: entry number (block 1, XXX-NNNNNNN-N) not found.")

    header["entry_date"] = _find_labeled_date(page1, "entry date")
    if header["entry_date"] is None:
        warnings.append("page 1: entry date (block 6) not found near an 'Entry Date' label.")

    for i, line in enumerate(page1):
        if "importer no" in line.lower():
            for candidate in page1[i:i + 3]:
                m = _IMPORTER_NO_RE.search(candidate)
                # Entry numbers also match loosely — don't misread block 1.
                if m and not _ENTRY_NO_RE.search(m.group(1)):
                    header["importer_no"] = m.group(1).strip()
                    break
            break

    # Block 10 header-level country of origin (line items may override).
    for i, line in enumerate(page1):
        if "country of origin" in line.lower():
            for candidate in [line[line.lower().index("country of origin") + 17:]] + page1[i + 1:i + 3]:
                m = re.search(r"\b([A-Z]{2})\b", candidate)
                if m and m.group(1) not in _UNIT_TOKENS:
                    header["origin"] = m.group(1)
                    break
            break

    return header


def _is_label_line(line):
    """Column-header/label rows must never be read as descriptions."""
    lowered = line.lower()
    return any(k in lowered for k in (
        "description of merchandise", "htsus", "gross weight", "net quantity",
        "entered value", "duty and ir tax", "line no",
    ))


def _split_line_item(line, hts_match):
    """Tokens before/after the HTS code on its line."""
    before = line[:hts_match.start()].split()
    after = line[hts_match.end():].split()
    return before, after


def _money(token):
    if not _MONEY_RE.match(token):
        return None
    try:
        value = float(token.lstrip("$").replace(",", ""))
    except ValueError:
        return None
    return value


def _value_and_duty(after_tokens):
    """Block 32 / block 34 relative to the block-33 rate anchor. Returns
    (declared_value, duty_paid, anchored)."""
    rate_idx = None
    for i, tok in enumerate(after_tokens):
        if _RATE_TOKEN_RE.match(tok):
            rate_idx = i
            break

    if rate_idx is not None:
        value = _money(after_tokens[rate_idx - 1]) if rate_idx > 0 else None
        duty = None
        for tok in after_tokens[rate_idx + 1:]:
            duty = _money(tok)
            if duty is not None:
                break
        return value, duty, True

    # No rate token — fall back to shape: duty is the last cents-bearing
    # number, entered value the largest of the rest. Caller adds a warning.
    numbers = [(i, _money(t)) for i, t in enumerate(after_tokens)]
    numbers = [(i, v) for i, v in numbers if v is not None]
    if not numbers:
        return None, None, False
    duty = None
    if len(numbers) >= 2 and "." in after_tokens[numbers[-1][0]]:
        duty = numbers[-1][1]
        numbers = numbers[:-1]
    value = max((v for _, v in numbers), default=None)
    return value, duty, False


def _line_context(page_no, line):
    snippet = line if len(line) <= 60 else line[:57] + "..."
    return f"page {page_no}: '{snippet}'"


def parse_7501(file_bytes):
    """Parse a CBP Form 7501 PDF into ES-003 rows for the batch audit.

    Returns {"header": {...}, "rows": [...], "warnings": [...]}.
    Raises NoExtractableTextError (scanned PDF) or NotA7501Error (no HTS
    line items)."""
    pages = _extract_pages(file_bytes)
    if not any(pages):
        raise NoExtractableTextError()

    warnings = []
    header = _parse_header(pages[0] if pages else [], warnings)

    rows = []
    for page_no, lines in enumerate(pages, start=1):
        for idx, line in enumerate(lines):
            matches = list(_HTS_CANDIDATE_RE.finditer(line))
            if not matches:
                continue
            for m in matches:
                code = m.group(1)
                digits = re.sub(r"\D", "", code)
                if len(digits) != 10:
                    warnings.append(
                        f"{_line_context(page_no, line)}: HTS-like token "
                        f"'{code}' is not a 10-digit code — skipped."
                    )
                    continue

                before, after = _split_line_item(line, m)

                # Line number: leading integer on the HTS line, else on the
                # preceding description row ("001 STAINLESS STEEL TUMBLERS").
                line_no = None
                description = None
                origin = None
                if before and before[0].isdigit() and len(before[0]) <= 3:
                    line_no = str(int(before[0]))
                    before = before[1:]
                if before and re.fullmatch(r"[A-Z]{2}", before[0]) and before[0] not in _UNIT_TOKENS:
                    origin = before[0]
                    before = before[1:]
                if before:
                    leftover = " ".join(before)
                    if re.search(r"[A-Za-z]{3,}", leftover):
                        description = leftover

                if line_no is None or description is None:
                    prev = lines[idx - 1] if idx > 0 else ""
                    pm = re.match(r"^(\d{1,3})\s+(.*\S)", prev)
                    if pm and not _is_label_line(prev) and not _HTS_CANDIDATE_RE.search(prev):
                        line_no = line_no or str(int(pm.group(1)))
                        if description is None and re.search(r"[A-Za-z]{3,}", pm.group(2)):
                            description = pm.group(2)

                if line_no is None:
                    line_no = str(len(rows) + 1)
                    warnings.append(
                        f"{_line_context(page_no, line)}: line number not found — "
                        f"assigned sequentially as {line_no}."
                    )

                value, duty, anchored = _value_and_duty(after)
                if not anchored and (value is not None or duty is not None):
                    warnings.append(
                        f"{_line_context(page_no, line)}: no rate column (block 33) "
                        "anchor — entered value/duty inferred by position; verify."
                    )
                if value is None:
                    warnings.append(
                        f"{_line_context(page_no, line)}: entered value (block 32) "
                        "not found — savings math will be skipped for this line."
                    )

                rows.append({
                    "row_id": line_no,
                    "entry_no": header["entry_no"],
                    "line_no": line_no,
                    "hts_code": code,
                    "description": description,
                    "origin": origin or header["origin"],
                    "declared_value": value,
                    "duty_paid": duty,
                    "entry_date": header["entry_date"],
                })

    if not rows:
        raise NotA7501Error()

    return {"header": header, "rows": rows, "warnings": warnings}
